/**
 * Pull the design tokens out of akaVST.
 *
 * Socket has to draw in the same language as the instruments it composes, and a
 * copied palette is one that will be wrong within a month — which is the whole
 * reason akaVST generates its tokens rather than writing them by hand.
 *
 * Reads the JSON that akaVST's own generator emits, so there is exactly one
 * source for the site, the plugins and this. Output is committed, so a clone
 * without akaVST beside it still builds and still looks right; it just cannot
 * pick up changes until someone runs this next to a checkout.
 *
 *   pnpm sync:tokens
 */

import fs from "node:fs";
import path from "node:path";

const ROOT = path.resolve(import.meta.dirname, "..");
const SOURCE = path.resolve(ROOT, "..", "akaVST", "web", "src", "content", "tokens.generated.json");
const OUT = path.join(ROOT, "src", "styles.css");

if (!fs.existsSync(SOURCE)) {
  console.error(`✗ no akaVST checkout beside this one — expected ${SOURCE}`);
  console.error("  the committed styles.css still works; this only refreshes it.");
  process.exit(1);
}

type Theme = { name: string; scheme: string; css: Record<string, string> };
const tokens = JSON.parse(fs.readFileSync(SOURCE, "utf-8")) as {
  radii: Record<string, string>;
  themes: Theme[];
};

const block = (selector: string, theme: Theme, radii: boolean) =>
  [
    `${selector} {`,
    `  color-scheme: ${theme.scheme};`,
    ...Object.entries(theme.css).map(([k, v]) => `  ${k}: ${v};`),
    ...(radii ? Object.entries(tokens.radii).map(([k, v]) => `  --${k}: ${v};`) : []),
    "}",
  ].join("\n");

const dark = tokens.themes.find((t) => t.scheme === "dark")!;
const light = tokens.themes.find((t) => t.scheme === "light")!;

fs.writeFileSync(
  OUT,
  `/* Generated by pnpm sync:tokens from akaVST. Do not edit. */

${block(":root", light, true)}

${block(".dark", dark, false)}

* { box-sizing: border-box; }

body {
  margin: 0;
  background: var(--background);
  color: var(--foreground);
  font-family: ui-sans-serif, system-ui, -apple-system, sans-serif;
  -webkit-font-smoothing: antialiased;
  overflow: hidden;
}

/* Mono for structure, sans for prose — the house rule. */
.label {
  font-family: ui-monospace, SFMono-Regular, Menlo, monospace;
  font-size: 0.625rem;
  letter-spacing: 0.18em;
  text-transform: uppercase;
  color: var(--muted-foreground);
  margin: 0;
}

.app { display: flex; flex-direction: column; height: 100vh; }

/* Depth is a hairline, never a shadow. */
.chrome {
  display: flex; align-items: baseline; gap: 1rem;
  padding: 0.9rem 1.25rem 0.9rem 5.5rem;
  border-bottom: 1px solid var(--hairline);
  -webkit-app-region: drag;
  flex: none;
}
.wordmark { font-size: 1rem; font-weight: 300; letter-spacing: 0.02em; }
.chrome-spacer { flex: 1; }

.workspace { flex: 1; display: grid; grid-template-columns: 210px 1fr 230px; min-height: 0; }

.rail {
  border-right: 1px solid var(--hairline);
  padding: 1rem;
  overflow: auto;
  -webkit-app-region: no-drag;
}
.rail-right { border-right: none; border-left: 1px solid var(--hairline); }

.palette { display: flex; flex-direction: column; gap: 0.35rem; margin-top: 0.75rem; }
.palette-item {
  display: flex; flex-direction: column; gap: 0.15rem;
  text-align: left; cursor: grab;
  background: var(--card-alpha);
  border: 1px solid var(--card-border);
  border-radius: var(--radius-pill);
  padding: 0.5rem 0.6rem;
  color: inherit; font: inherit;
}
.palette-item:hover { border-color: var(--card-border-hover); background: var(--card); }
.palette-item:active { cursor: grabbing; }
.palette-name { font-size: 0.8rem; }
.palette-from {
  font-family: ui-monospace, Menlo, monospace;
  font-size: 0.6rem; color: var(--muted-foreground);
}

.stage { padding: 1.25rem; overflow: auto; }
.stage-label { margin-bottom: 0.75rem; }

/* The plugin face: a grid of panels, the way the instruments lay out. */
.face {
  display: grid;
  grid-template-columns: repeat(12, 1fr);
  gap: 0.6rem;
  align-content: start;
  min-height: 200px;
}
.empty {
  grid-column: span 12;
  color: var(--muted-foreground);
  font-size: 0.85rem;
  border: 1px dashed var(--card-border);
  border-radius: var(--radius-card);
  padding: 2.5rem; text-align: center;
}

.panel {
  border: 1px solid var(--card-border);
  border-radius: var(--radius-card);
  background: var(--card-alpha);
  padding: 0.55rem 0.7rem 0.8rem;
  min-width: 0;
}
.panel-selected { border-color: var(--accent-blue); }

.panel-head { display: flex; align-items: center; gap: 0.4rem; }
/* One tinted mark, the way the instruments label a module. */
.panel-tab { width: 3px; height: 11px; background: var(--accent-blue); border-radius: 1px; }
.panel-remove {
  margin-left: auto; background: none; border: none; cursor: pointer;
  color: var(--muted-foreground); font-size: 0.95rem; line-height: 1; padding: 0 2px;
}
.panel-remove:hover { color: var(--foreground); }

.panel-body {
  display: flex; flex-wrap: wrap; gap: 0.7rem;
  margin-top: 0.7rem; align-items: flex-start;
}

.knob { display: flex; flex-direction: column; align-items: center; gap: 0.2rem; }
.knob-label {
  font-family: ui-monospace, Menlo, monospace;
  font-size: 0.55rem; letter-spacing: 0.1em; text-transform: uppercase;
  color: var(--muted-foreground);
}

.choice { display: flex; flex-direction: column; align-items: center; gap: 0.2rem; }
.choice-box {
  font-family: ui-monospace, Menlo, monospace; font-size: 0.68rem;
  padding: 0.3rem 0.55rem;
  border: 1px solid var(--card-border);
  border-radius: var(--radius-pill);
  background: var(--card);
  min-width: 54px; text-align: center;
}

.screen { width: 100%; height: 62px; display: block; }

.hint { font-size: 0.75rem; color: var(--muted-foreground); margin: 0.5rem 0 0; line-height: 1.5; }
.section { margin-top: 1.25rem; }

.span-row { display: flex; gap: 0.25rem; margin-top: 0.5rem; }
.span-btn {
  flex: 1; padding: 0.3rem 0; cursor: pointer;
  font-family: ui-monospace, Menlo, monospace; font-size: 0.65rem;
  background: var(--card-alpha); color: var(--muted-foreground);
  border: 1px solid var(--card-border); border-radius: var(--radius-pill);
}
.span-btn.on { background: var(--accent-blue); color: var(--primary-foreground); border-color: var(--accent-blue); }

.param { display: flex; align-items: center; gap: 0.5rem; margin-top: 0.55rem; }
.param-name {
  font-family: ui-monospace, Menlo, monospace; font-size: 0.62rem;
  color: var(--muted-foreground); width: 46px; flex: none;
}
.param input[type="range"] { flex: 1; accent-color: var(--accent-blue); }
.param-value { font-family: ui-monospace, Menlo, monospace; font-size: 0.7rem; }
`
);

console.log(`✓ ${path.relative(ROOT, OUT)}`);
