/**
 * Pull the design tokens out of akaVST.
 *
 * Socket has to draw in the same language as the instruments it composes, and a
 * copied palette is one that will be wrong within a month — which is the whole
 * reason akaVST generates its tokens rather than writing them by hand.
 *
 * Reads the JSON that akaVST's own generator emits, so there is exactly one
 * source for the site, the plugins and this. Output is committed, so a clone
 * without akaVST beside it still builds and still looks right; it just cannot
 * pick up changes until someone runs this next to a checkout.
 *
 *   pnpm sync:tokens
 */

import fs from "node:fs";
import path from "node:path";

const ROOT = path.resolve(import.meta.dirname, "..");
const SOURCE = path.resolve(ROOT, "..", "akaVST", "web", "src", "content", "tokens.generated.json");
const OUT = path.join(ROOT, "src", "styles.css");

if (!fs.existsSync(SOURCE)) {
  console.error(`✗ no akaVST checkout beside this one — expected ${SOURCE}`);
  console.error("  the committed styles.css still works; this only refreshes it.");
  process.exit(1);
}

type Theme = { name: string; scheme: string; css: Record<string, string> };
const tokens = JSON.parse(fs.readFileSync(SOURCE, "utf-8")) as {
  radii: Record<string, string>;
  themes: Theme[];
};

/**
 * The canvas the plugin window sits on.
 *
 * Socket-only, so it is derived here rather than added to akaVST's tokens — the
 * site has no plugin canvas to put behind anything. Without it the stage and the
 * plugin are the same colour and the window does not read as sitting on a
 * surface at all; it reads as the app having a border in the middle of it.
 *
 * Both are the theme's own ink at low alpha over the app background, which is
 * the convention every other surface token here already follows. Dark recesses
 * (the plugin is the lit thing); paper deepens toward grey (the plugin is the
 * white sheet). The 107 hue at near-zero chroma keeps them untinted.
 */
const STAGE: Record<string, [string, string]> = {
  // scheme: [stage surface, the grid dot on it]
  dark: ["oklch(0.1 0.002 107)", "oklch(1 0 0 / 5%)"],
  light: ["oklch(0.885 0.003 107)", "oklch(0.19 0.01 95 / 9%)"],
};

const block = (selector: string, theme: Theme, radii: boolean) =>
  [
    `${selector} {`,
    `  color-scheme: ${theme.scheme};`,
    ...Object.entries(theme.css).map(([k, v]) => `  ${k}: ${v};`),
    ...(radii ? Object.entries(tokens.radii).map(([k, v]) => `  --${k}: ${v};`) : []),
    `  --stage: ${STAGE[theme.scheme]![0]};`,
    `  --stage-dot: ${STAGE[theme.scheme]![1]};`,
    ...SIDEBAR_ALIASES.map(([k, v]) => `  ${k}: ${v};`),
    "}",
  ].join("\n");

const dark = tokens.themes.find((t) => t.scheme === "dark")!;
const light = tokens.themes.find((t) => t.scheme === "light")!;

/**
 * shadcn's sidebar components read their own token names.
 *
 * Aliased onto tokens akaVST already emits rather than given values of their
 * own — a second palette living beside the first is exactly the drift the
 * generator exists to prevent. Every shadcn component that lands in this app
 * therefore arrives already wearing akaSTYLE, with nothing to restyle by hand.
 */
const SIDEBAR_ALIASES: Array<[string, string]> = [
  ["--sidebar", "var(--background)"],
  ["--sidebar-foreground", "var(--foreground)"],
  ["--sidebar-primary", "var(--primary)"],
  ["--sidebar-primary-foreground", "var(--primary-foreground)"],
  ["--sidebar-accent", "var(--card-alpha)"],
  ["--sidebar-accent-foreground", "var(--foreground)"],
  ["--sidebar-border", "var(--hairline)"],
  ["--sidebar-ring", "var(--ring)"],
];

/** Tailwind utility names, pointed at the variables above. */
const TW_COLORS = [
  "background", "foreground", "card", "card-foreground", "popover", "popover-foreground",
  "primary", "primary-foreground", "secondary", "secondary-foreground",
  "muted", "muted-foreground", "accent", "accent-foreground", "destructive",
  "border", "input", "ring",
  "accent-blue", "accent-green", "accent-amber", "accent-rose", "accent-violet",
  "border-strong", "card-alpha", "card-border", "card-border-hover", "hairline",
  "mark-panel", "mark-screen", "stage", "stage-dot",
  "sidebar", "sidebar-foreground", "sidebar-primary", "sidebar-primary-foreground",
  "sidebar-accent", "sidebar-accent-foreground", "sidebar-border", "sidebar-ring",
];

fs.writeFileSync(
  OUT,
  `/* Generated by pnpm sync:tokens from akaVST. Do not edit. */

@import "tailwindcss";
@import "tw-animate-css";

@custom-variant dark (&:is(.dark *));

${block(":root", light, true)}

${block(".dark", dark, false)}

/* Tailwind, and therefore every shadcn component, drawing from the generated
   palette. No component in this app has a colour of its own. */
@theme inline {
${TW_COLORS.map((c) => `  --color-${c}: var(--${c});`).join("\n")}

  --radius-sm: calc(var(--radius) * 0.6);
  --radius-md: calc(var(--radius) * 0.8);
  --radius-lg: var(--radius);
  --radius-xl: calc(var(--radius) * 1.4);
}

* { box-sizing: border-box; }

body {
  margin: 0; overflow: hidden;
  background: var(--background); color: var(--foreground);
  font-family: ui-sans-serif, system-ui, -apple-system, sans-serif;
  -webkit-font-smoothing: antialiased;
}
button { font: inherit; color: inherit; }

/* Mono for structure, sans for prose — the house rule. */
.label {
  font-family: ui-monospace, SFMono-Regular, Menlo, monospace;
  font-size: 0.6rem; letter-spacing: 0.18em; text-transform: uppercase;
  color: var(--muted-foreground); margin: 0;
}

/* Electron draws no chrome, so the title bar has to be one: the empty parts of
   that row move the window and every control opts back out. Without this you
   cannot grab the top of the window at all. */
.drag-region { -webkit-app-region: drag; }
/* The traffic lights float over the app at the top left, which is now the
   sidebar. Their room comes out of its header, and nothing may sit there. */
[data-slot="sidebar-header"] { padding-top: 30px; -webkit-app-region: drag; }
[data-slot="sidebar-header"] > * { -webkit-app-region: no-drag; }
.drag-region button,
.drag-region input,
.drag-region [role="group"],
.no-drag { -webkit-app-region: no-drag; }

.hint { font-size: 0.72rem; color: var(--muted-foreground); margin: 0.45rem 0 0; line-height: 1.5; }

/* ── palette ───────────────────────────────────────────────────────── */
.palette { display: flex; flex-direction: column; gap: 0.3rem; margin-top: 0.5rem; }
.palette-item {
  display: flex; flex-direction: column; gap: 0.1rem; text-align: left; cursor: grab;
  background: var(--card-alpha); border: 1px solid var(--card-border);
  border-radius: var(--radius-pill); padding: 0.42rem 0.55rem;
}
.palette-item:hover { border-color: var(--card-border-hover); background: var(--card); }
.palette-name { font-size: 0.78rem; }
.palette-from { font-family: ui-monospace, Menlo, monospace; font-size: 0.56rem; color: var(--muted-foreground); }

/* ── the plugin window ─────────────────────────────────────────────── */
/* The canvas. A dot grid on its own surface, so the plugin window reads as an
   object placed on something rather than as a rectangle drawn on the app. The
   grid also gives the eye a fixed reference while a panel is being dragged. */
.stage {
  flex: 1; min-height: 0; display: flex; align-items: center; justify-content: center;
  background-color: var(--stage);
  background-image: radial-gradient(var(--stage-dot) 1px, transparent 1px);
  background-size: 16px 16px;
  background-position: -1px -1px;
}
/* Same surface behind the routing matrix, so switching views does not switch
   the room you are standing in. */
.scroll { background: var(--stage); }
.frame-scaler { position: relative; flex: none; }
/* The one shadow in the app. Everywhere else depth is a border — that is the
   house rule and it holds for cards sitting *in* a layout. This is a window
   sitting *on* a canvas, which is a different claim, and it is the claim every
   DAW makes about a plugin. Kept soft: the border still does most of the work. */
.frame {
  position: absolute; top: 0; left: 0; transform-origin: top left;
  display: flex; flex-direction: column;
  background: var(--background);
  border: 1px solid var(--border-strong); border-radius: 10px; overflow: hidden;
  box-shadow: 0 1px 2px oklch(0 0 0 / 18%), 0 18px 48px -12px oklch(0 0 0 / 38%);
}
.frame-head {
  display: flex; align-items: center; gap: 14px; flex: none;
  padding: 0 14px; height: 42px; border-bottom: 1px solid var(--hairline);
}
.frame-word { font-size: 15px; font-weight: 300; letter-spacing: 0.06em; }
.frame-preset {
  font-family: ui-monospace, Menlo, monospace; font-size: 11px;
  color: var(--muted-foreground);
  border: 1px solid var(--card-border); border-radius: 5px; padding: 4px 40px;
}
.frame-tabs { display: flex; gap: 3px; }
.frame-tab {
  font-family: ui-monospace, Menlo, monospace; font-size: 10px;
  letter-spacing: 0.12em; text-transform: uppercase; cursor: pointer;
  padding: 5px 14px; border: none; border-radius: 4px;
  color: var(--muted-foreground); background: var(--card-alpha);
}
.frame-tab.on { background: var(--plugin-accent); color: var(--primary-foreground); }
.frame-meter {
  margin-left: auto; width: 120px; height: 5px; border-radius: 3px;
  background: linear-gradient(90deg, var(--plugin-accent) 40%, var(--card) 40%);
}
/* Twelve columns and an 8px row unit. Rows are explicit because a width-only
   block makes every row as tall as its tallest member, which is why the first
   layouts came out as uniform horizontal bands — the grid was doing the
   composing rather than the person. */
.frame-body {
  flex: 1; min-height: 0; overflow: auto; padding: 12px;
  display: grid; grid-template-columns: repeat(12, 1fr);
  grid-auto-rows: 8px; gap: 8px; align-content: start;
  /* Dense, so a short block backfills the hole a tall one leaves beside it.
     Sparse placement is what turns a mixed-height bento into a column of gaps,
     and a gap you did not ask for is the dead space this was meant to fix. */
  grid-auto-flow: row dense;
}
.frame-foot {
  flex: none; height: 22px; display: flex; align-items: center; gap: 16px;
  padding: 0 14px; border-top: 1px solid var(--hairline);
  font-family: ui-monospace, Menlo, monospace; font-size: 9px;
  letter-spacing: 0.1em; color: var(--muted-foreground);
}
.empty {
  grid-column: span 12; grid-row: span 8; color: var(--muted-foreground); font-size: 13px;
  border: 1px dashed var(--card-border); border-radius: var(--radius-card);
  padding: 2.5rem; text-align: center;
}

/* ── a block on the face ───────────────────────────────────────────── */
/* The panel is a query container, so everything inside sizes off the panel
   rather than off the window. A four-knob envelope stretched to half the plugin
   used to leave two thirds of itself empty: the fix is not more knobs, it is
   controls that grow into the room they are given, which is what hardware does
   and what a fixed pixel size in JS can never do.
   A flex column, so height behaves the same way — the face takes what is left
   over and the controls sit under it, instead of everything hugging the top
   with a hole beneath. */
.panel {
  container-type: inline-size;
  position: relative; min-width: 0; min-height: 0; overflow: hidden;
  display: flex; flex-direction: column;
  border: 1px solid var(--card-border); border-radius: var(--radius-card);
  background: var(--card-alpha); padding: 7px 9px 10px;
}
.panel-selected { border-color: var(--plugin-accent); }
.panel-dragging { opacity: 0.4; }
/* The header is the handle: a window is dragged by its title bar so that
   reaching for a control inside it does not move the window. */
.panel-head { display: flex; align-items: center; gap: 6px; flex: none; cursor: grab; }
.panel-head:active { cursor: grabbing; }
.panel-tab { width: 3px; height: 11px; border-radius: 1px; background: var(--plugin-accent); flex: none; }
.panel-wired { width: 5px; height: 5px; border-radius: 999px; background: var(--accent-green); }
.panel-remove {
  margin-left: auto; background: none; border: none; cursor: pointer;
  color: var(--muted-foreground); font-size: 15px; line-height: 1; padding: 0 2px;
}
.panel-remove:hover { color: var(--foreground); }
/* Controls distribute across the panel rather than clustering at its left edge.
   The gap is the floor, not the spacing: on a narrow panel it decides, on a wide
   one the free space is shared out and six knobs read as a laid-out row instead
   of a huddle with a third of the panel empty beside it. */
.panel-body {
  flex: none; display: flex; flex-wrap: wrap; align-items: flex-start;
  align-content: center; justify-content: space-evenly;
  gap: clamp(9px, 2.6cqi, 30px); margin-top: 9px;
}
/* With no face above them the controls own the whole panel, so extra height
   reads as breathing room rather than as a gap under a huddle. */
.panel-body-fill { flex: 1; min-height: 0; }
/* One control has no distribution to do, and centring it in a wide panel just
   strands it. */
.panel-body:has(> :only-child) { justify-content: flex-start; }
/* Resize by the edge: dragging one is laying out, a row of buttons only
   describes a layout. Right for columns, bottom for rows, corner for both. */
.grip { position: absolute; z-index: 2; }
.grip::after {
  content: ""; position: absolute; inset: 0; opacity: 0;
  background: var(--plugin-accent); transition: opacity 120ms ease;
}
.grip:hover::after, .grip:active::after { opacity: 0.35; }
.grip-x {
  top: 0; right: 0; width: 8px; height: 100%; cursor: ew-resize;
  border-radius: 0 var(--radius-card) var(--radius-card) 0;
}
.grip-y {
  left: 0; bottom: 0; height: 8px; width: 100%; cursor: ns-resize;
  border-radius: 0 0 var(--radius-card) var(--radius-card);
}
.grip-xy {
  right: 0; bottom: 0; width: 16px; height: 16px; cursor: nwse-resize;
  border-radius: 0 0 var(--radius-card) 0;
}
/* The corner earns a mark, because a corner with no affordance is one nobody
   finds. Three pips, in the pixel grammar. */
.grip-xy::before {
  content: ""; position: absolute; right: 3px; bottom: 3px; width: 8px; height: 8px;
  opacity: 0.55;
  background:
    linear-gradient(var(--muted-foreground) 0 0) 100% 100% / 2px 2px no-repeat,
    linear-gradient(var(--muted-foreground) 0 0) 100% 40% / 2px 2px no-repeat,
    linear-gradient(var(--muted-foreground) 0 0) 40% 100% / 2px 2px no-repeat;
}

.knob { display: flex; flex-direction: column; align-items: center; gap: 3px; }
.knob svg { display: block; width: clamp(34px, 6.5cqi, 62px); height: auto; }
.knob-label {
  font-family: ui-monospace, Menlo, monospace; font-size: clamp(8px, 1.1cqi, 11px);
  letter-spacing: 0.1em; text-transform: uppercase; color: var(--muted-foreground);
}
.choice { display: flex; flex-direction: column; align-items: center; gap: 3px; }
.choice-box, .toggle-box {
  font-family: ui-monospace, Menlo, monospace; cursor: pointer; text-align: center;
  font-size: clamp(10px, 1.3cqi, 13px);
  padding: clamp(5px, 0.9cqi, 9px) clamp(9px, 1.8cqi, 18px);
  min-width: clamp(54px, 10cqi, 84px);
  border: 1px solid var(--card-border); border-radius: var(--radius-pill);
  background: var(--card); color: var(--foreground);
}
.toggle-box.on { background: var(--plugin-accent); color: var(--primary-foreground); border-color: var(--plugin-accent); }
.screen { width: 100%; display: block; }
.meter-block { display: flex; gap: 2px; align-items: flex-end; height: 40px; }
.meter-seg { width: 5px; height: 100%; background: var(--plugin-accent); border-radius: 1px; }

/* ── signal view ───────────────────────────────────────────────────── */
.signal { max-width: 900px; }
.matrix { display: grid; gap: 3px; margin-top: 0.75rem; align-items: center; }
.matrix-col {
  font-family: ui-monospace, Menlo, monospace; font-size: 0.56rem;
  text-transform: uppercase; letter-spacing: 0.08em;
  color: var(--muted-foreground); text-align: center; padding-bottom: 4px;
}
.matrix-col.dim { opacity: 0.35; }
.matrix-row {
  display: flex; flex-direction: column; gap: 1px; text-align: left; cursor: pointer;
  background: var(--card-alpha); border: 1px solid var(--card-border);
  border-radius: var(--radius-pill); padding: 0.35rem 0.5rem; font-size: 0.75rem;
}
.matrix-row.on { border-color: var(--accent-blue); }
.matrix-from { font-family: ui-monospace, Menlo, monospace; font-size: 0.54rem; color: var(--muted-foreground); }
.cell {
  height: 30px; cursor: pointer;
  background: var(--card-alpha); border: 1px solid var(--card-border); border-radius: 5px;
}
.cell:hover:not(:disabled) { border-color: var(--accent-blue); }
.cell.wired { background: var(--accent-blue); border-color: var(--accent-blue); }
.cell.illegal { opacity: 0.16; cursor: default; }

.mod-row { display: flex; flex-wrap: wrap; gap: 0.35rem; margin-top: 0.6rem; }
.mod-chip {
  cursor: pointer; font-size: 0.75rem; padding: 0.3rem 0.6rem;
  background: var(--card-alpha); border: 1px solid var(--card-border);
  border-radius: var(--radius-pill);
}
.accent-row { display: flex; gap: 0.4rem; margin-top: 0.55rem; }
.accent-dot {
  width: 20px; height: 20px; border-radius: 999px; cursor: pointer;
  border: 2px solid transparent; padding: 0;
}
.accent-dot.on { border-color: var(--foreground); }

/* ── faces ─────────────────────────────────────────────────────────────
   Everything a block draws that is not a knob. Each one is sized in the
   plugin's own pixels, not the app's: these are drawn inside the scaled
   frame, so a value here is a value in the built plugin. */
/* The face absorbs whatever height is left over. Dragging a panel taller makes
   its screen bigger, which is the only sane answer to what the extra room is
   for — a display pinned to 62px inside a panel twice as tall just opens a gap
   under itself. The clamps below are floors, not sizes. */
.panel-face { flex: 1; min-height: 0; margin-top: 8px; display: flex; }
.panel-face > * { flex: 1; min-height: 0; min-width: 0; }
.face-canvas { display: block; width: 100%; height: 100%; }
.face-screen   { min-height: clamp(46px, 9cqi, 96px); }
.face-scope    { min-height: clamp(42px, 8cqi, 88px); }
.face-spectrum { min-height: clamp(40px, 8cqi, 88px); }
.face-curve    { min-height: clamp(38px, 7cqi, 80px); }
.face-meter    { min-height: 44px; flex: none; width: clamp(30px, 5cqi, 46px); }

.fader { display: flex; flex-direction: column; align-items: center; gap: 4px; }
.fader-track {
  position: relative; width: clamp(14px, 2.2cqi, 22px); height: clamp(44px, 10cqi, 84px);
  background: var(--mark-panel); border: 1px solid var(--card-border); border-radius: 3px;
}
.fader-fill {
  position: absolute; left: 0; right: 0; bottom: 0;
  background: var(--plugin-accent); opacity: 0.28; border-radius: 0 0 2px 2px;
}
.fader-cap {
  position: absolute; left: -2px; right: -2px; height: 6px;
  background: var(--foreground); border-radius: 2px;
}

/* ── the patch bay ─────────────────────────────────────────────────────
   Jacks down each side and a cable between them. It was a matrix of dots,
   which is a fine editor and a poor instrument: a filled cell six rows from
   its label reads as a value in a spreadsheet, not as a route. The whole
   point of a patch bay is that the routing is the thing you can see. */
.patchbay { position: relative; display: flex; width: 100%; min-height: 78px; }
.patch-side {
  display: flex; flex-direction: column; justify-content: space-around;
  z-index: 2; flex: none;
}
.patch-src { align-items: flex-start; }
.patch-dst { align-items: flex-end; margin-left: auto; }

.patch-jack {
  display: flex; align-items: center; gap: 4px; padding: 0; cursor: grab;
  background: none; border: none; color: var(--muted-foreground);
}
.patch-jack:active { cursor: grabbing; }
.patch-label {
  font-family: ui-monospace, Menlo, monospace; font-size: clamp(7px, 1cqi, 10px);
  letter-spacing: 0.08em; color: var(--muted-foreground);
}
.patch-jack.on .patch-label { color: var(--foreground); }

/* A socket, not a dot: a ring with a dark centre reads as something a plug
   goes into, which is the affordance the whole face depends on. */
.patch-hole {
  width: clamp(9px, 1.6cqi, 14px); height: clamp(9px, 1.6cqi, 14px);
  border-radius: 999px; flex: none;
  background: var(--mark-screen);
  border: 2px solid var(--card-border-hover);
  box-shadow: inset 0 0 0 1px var(--background);
}
.patch-jack.on .patch-hole { border-color: currentColor; background: currentColor; }
.patch-jack:hover .patch-hole { border-color: currentColor; }
/* A jack with nothing behind it. Drawn, not hidden: the panel keeps its shape,
   and you can see that the cable you want needs a block you have not placed. */
.patch-jack.dead { cursor: default; opacity: 0.32; }
.patch-jack.dead:hover .patch-hole { border-color: var(--card-border-hover); }

.patch-wires {
  position: absolute; inset: 0; width: 100%; height: 100%;
  z-index: 1; overflow: visible;
}
.patch-cable {
  fill: none; stroke-width: 2.5; stroke-linecap: round;
  vector-effect: non-scaling-stroke; cursor: pointer;
  pointer-events: stroke;
}
.patch-cable:hover { stroke-width: 4; }
/* The cable in flight follows the pointer and must not eat the drop. */
.patch-dragging { pointer-events: none; opacity: 0.7; stroke-dasharray: 4 3; }

/* ── the step grid ─────────────────────────────────────────────────────
   Pads in eight by two, not sixteen thin bars. That is bleep's shape and it
   is the right one: a pad is big enough to carry its own step number and to
   show its velocity as fill, and two rows of eight is how anyone who has
   used a drum machine already counts a bar. */
.seq { display: flex; flex-direction: column; gap: 4px; width: 100%; min-height: 0; }

.seq-transport, .seq-lanes { display: flex; align-items: center; gap: 2px; flex: none; }
.seq-gap { flex: 1; }

.seq-play, .seq-gen, .seq-lane, .seq-page-nav {
  font-family: ui-monospace, Menlo, monospace; font-size: clamp(7px, 0.95cqi, 10px);
  letter-spacing: 0.06em; cursor: pointer; padding: 2px 5px;
  background: var(--card-alpha); color: var(--muted-foreground);
  border: 1px solid var(--card-border); border-radius: 3px;
}
.seq-play { min-width: 38px; }
.seq-play.on { background: var(--accent-green); color: var(--primary-foreground); border-color: var(--accent-green); }
.seq-lane.on { background: var(--plugin-accent); color: var(--primary-foreground); border-color: var(--plugin-accent); }
.seq-gen:hover, .seq-page-nav:hover { color: var(--foreground); border-color: var(--card-border-hover); }

.seq-page, .seq-len, .seq-hint {
  font-family: ui-monospace, Menlo, monospace; font-size: clamp(7px, 0.95cqi, 10px);
  color: var(--muted-foreground); padding: 0 3px; white-space: nowrap;
}
.seq-hint { opacity: 0.6; }

/* Always eight by two. bleep shows a sixteen-step page that way at every
   width, and it is right: a pad wider than it is tall reads as a bar of music,
   and two rows of eight is how anyone who has used a drum machine already
   counts one. Sixteen across turns each pad portrait, which reads as a level
   meter. The rows are capped so a tall panel gives the pads breathing room
   rather than turning them into columns. */
.seq-grid {
  display: grid;
  grid-template-columns: repeat(8, minmax(0, 1fr));
  grid-template-rows: repeat(2, minmax(0, 1fr));
  gap: 3px; flex: 1; min-height: clamp(34px, 6cqi, 76px); max-height: 96px;
}

.seq-pad {
  position: relative; padding: 0; cursor: ns-resize; overflow: hidden;
  background: var(--mark-panel);
  border: 1px solid var(--card-border); border-radius: 3px;
}
/* Velocity as fill. A pad you can read the dynamics of across a whole bar
   without clicking anything, which is what makes bleep's grid legible. */
.seq-pad.on {
  background: color-mix(in oklch, var(--plugin-accent) calc(var(--fill, 1) * 78%), var(--mark-screen));
  border-color: transparent;
}
.seq-pad.head { box-shadow: inset 0 0 0 2px var(--foreground); }
/* Past the pattern length: still editable, visibly not playing. */
.seq-pad.past { opacity: 0.35; }
.seq-pad:nth-child(4n + 1) { border-left: 1px solid var(--card-border-hover); }

.seq-num {
  position: absolute; top: 1px; left: 3px;
  font-family: ui-monospace, Menlo, monospace; font-size: clamp(6px, 0.85cqi, 9px);
  color: var(--muted-foreground); pointer-events: none;
}
.seq-pad.on .seq-num { color: var(--primary-foreground); opacity: 0.75; }
.seq-val {
  position: absolute; inset: auto 0 2px 0; text-align: center;
  font-family: ui-monospace, Menlo, monospace; font-size: clamp(6px, 0.9cqi, 10px);
  color: var(--primary-foreground); opacity: 0.85; pointer-events: none;
}

.xy {
  position: relative; width: 100%; min-height: clamp(56px, 11cqi, 120px); cursor: crosshair;
  background: var(--mark-panel); border: 1px solid var(--card-border);
  border-radius: 4px; overflow: hidden;
}
.xy-cross { position: absolute; background: var(--card-border); }
.xy-guide { position: absolute; background: var(--hairline); }
.xy-h { left: 0; right: 0; height: 1px; }
.xy-v { top: 0; bottom: 0; width: 1px; }
.xy-guide.xy-h { left: 0; right: 0; height: 1px; }
.xy-guide.xy-v { top: 0; bottom: 0; width: 1px; }
.xy-dot {
  position: absolute; width: 9px; height: 9px; margin: -4.5px 0 0 -4.5px;
  border-radius: 999px; background: var(--plugin-accent);
}

.keys {
  position: relative; width: 100%; min-height: clamp(36px, 7cqi, 80px);
  background: var(--mark-panel); border: 1px solid var(--card-border);
  border-radius: 3px; overflow: hidden;
}
.keys .key-w, .keys .key-b { position: absolute; top: 0; padding: 0; cursor: pointer; }
/* Two fixed greys rather than theme tokens. Everywhere else in the system a
   surface follows the theme, but on a keyboard the light/dark contrast IS the
   affordance — driven by --foreground the black keys came out bright in dark
   mode and the white keys vanished into the chassis. Both sit on the same 107
   hue at near-zero chroma, so no new colour enters the system. */
.keys .key-w {
  height: 100%; background: oklch(0.86 0.003 107);
  border: none; border-right: 1px solid oklch(0.19 0.01 95 / 22%);
}
.keys .key-b {
  height: 60%; background: oklch(0.24 0.003 107); border: none;
  border-radius: 0 0 2px 2px; transform: translateX(-31%); z-index: 1;
}
.keys .key-w.on, .keys .key-b.on { background: var(--plugin-accent); }

/* Fixed pad height rather than a square aspect: square pads in a fluid
   four-column grid grow with the panel, and a 4-wide panel gave a pad grid
   taller than the plugin window. */
.pads { display: grid; gap: 3px; width: 100%; align-content: center; }
.pads .pad {
  height: clamp(18px, 3.4cqi, 34px); padding: 0; cursor: pointer;
  background: var(--mark-panel); border: 1px solid var(--card-border); border-radius: 3px;
}
.pads .pad:hover { border-color: var(--card-border-hover); }
.pads .pad.on { background: var(--plugin-accent); border-color: var(--plugin-accent); }

.readout {
  width: 100%; align-self: center; padding: clamp(6px, 1.2cqi, 12px) clamp(8px, 1.6cqi, 16px);
  background: var(--mark-screen); border-radius: 4px;
  font-family: ui-monospace, Menlo, monospace; font-size: clamp(9px, 1.3cqi, 13px);
  letter-spacing: 0.06em; color: var(--muted-foreground);
}
.readout-row { display: flex; justify-content: space-between; line-height: 1.7; }
.readout-v { color: var(--plugin-accent); }

/* ── the block list ────────────────────────────────────────────────────
   Forty-nine blocks flat is a column you scroll past rather than read. Six
   labelled rows is something you take in at a glance and then open. */
.palette-search { margin-bottom: 0.6rem; }

.group + .group { margin-top: 2px; }
.group-head {
  display: flex; align-items: center; gap: 0.55rem; width: 100%;
  padding: 0.4rem 0.15rem; cursor: pointer;
  background: none; border: none; border-radius: var(--radius-pill);
  color: var(--muted-foreground);
}
.group-head:hover { color: var(--foreground); }
.group-head.open { color: var(--foreground); }
.group-name {
  flex: 1; text-align: left;
  font-family: ui-monospace, SFMono-Regular, Menlo, monospace;
  font-size: 0.62rem; letter-spacing: 0.16em; text-transform: uppercase;
}
.group-count {
  font-family: ui-monospace, Menlo, monospace; font-size: 0.58rem;
  color: var(--muted-foreground);
}
.pixel-icon { flex: none; fill: currentColor; }
.group-head.open .pixel-icon { fill: var(--accent-blue); }

.palette { display: flex; flex-direction: column; gap: 2px; margin: 0.15rem 0 0.6rem; }
.palette-item {
  display: block; text-align: left; cursor: grab; font-size: 0.78rem;
  background: none; border: 1px solid transparent;
  border-radius: var(--radius-pill); padding: 0.3rem 0.55rem;
}
.palette-item:hover { background: var(--card-alpha); border-color: var(--card-border); }
.palette-item.stub { color: var(--muted-foreground); }
`
);

console.log(`✓ ${path.relative(ROOT, OUT)}`);
