/**
 * Emit the block catalogue into the places that are not TypeScript.
 *
 * The catalogue is the contract between the UI and the DSP: a block's id, and
 * the order of its parameters. Socket sends `(blockIndex, paramIndex, value)`
 * and the engine's switch reads that index — nothing else keeps the two in
 * step, and a parameter inserted in the middle of a block silently re-addresses
 * every one after it. You would hear it, eventually, as the wrong knob doing
 * something.
 *
 * Same contract as sync-tokens.mts, in the other direction: output is
 * committed, no build depends on this having run, and `--check` fails if the
 * tree disagrees.
 *
 *   pnpm sync:blocks
 *   pnpm check:blocks
 */

import fs from "node:fs";
import path from "node:path";
import { CATALOG } from "../src/model/catalog.ts";
import type { BlockDef } from "../src/model/types.ts";


const ROOT = path.resolve(import.meta.dirname, "..");
const SKELETON = path.resolve(ROOT, "..", "akaVST", "skeleton", "modules", "aka_skeleton", "dsp");
const HEADER = path.join(SKELETON, "BlockCatalog.h");
const TS_OUT = path.join(ROOT, "src", "audio", "blocks.generated.ts");

/** `fx chain` and `xy pad` are not identifiers. */
const ident = (s: string) => s.replace(/[^a-zA-Z0-9]+(.)?/g, (_, c) => (c ? c.toUpperCase() : ""));

/**
 * Where a block runs.
 *
 * Derived from the group rather than declared, because for forty-seven of the
 * forty-nine the group already answers it: a Source, Shape or Modulate block
 * belongs to a voice, an Effect or Route block runs once on the sum. The two
 * that are genuinely either — a Route block that is really a per-voice setting —
 * are handled by the engine choosing not to implement one of the two factories.
 */
const isVoice = (d: BlockDef) =>
  d.group === "Source" || d.group === "Shape" || d.group === "Modulate";

/* ── C++ ──────────────────────────────────────────────────────────────── */

function emitHeader(): string {
  const entries = CATALOG.map((d, i) => ({ def: d, id: ident(d.type), index: i + 1 }));

  const enumBody = entries
    .map(({ id, index, def }) => `    ${id.padEnd(12)} = ${String(index).padStart(2)},  // ${def.name}`)
    .join("\n");

  const table = entries
    .map(({ def, id }) =>
      `    { "${def.type}", "${def.name}", ${isVoice(def) ? "true " : "false"}, ${String(def.params.length).padStart(2)} },  // ${id}`,
    )
    .join("\n");

  const params = entries
    .filter(({ def }) => def.params.length > 0)
    .map(({ def, id }) =>
      `//   ${id}: ${def.params.map((p, i) => `${i}=${p.label}`).join(", ")}`)
    .join("\n");

  return `#pragma once

// GENERATED by Socket/scripts/sync-blocks.mts — do not edit.
// Source of truth: Socket/src/model/catalog.ts. Run \`pnpm sync:blocks\` in Socket.
//
// The contract between the interface and the DSP. Socket addresses a parameter
// as (block index, parameter index) and the engine's switch reads that index;
// nothing else keeps the two in step. A parameter inserted into the middle of a
// block would silently re-address every one after it, and you would hear it
// eventually as the wrong knob doing something.
//
// Every block in the catalogue gets a value here, including the ones with no
// engine yet. That way implementing one never renumbers the others.
//
// Parameter order, for writing setParam against:
//
${params}

namespace aka::dsp
{

enum class BlockType
{
    none         =  0,
${enumBody}
    numTypes
};

struct BlockInfo
{
    const char* id;
    const char* name;
    /** True if the block belongs to a voice; false if it runs on the sum. */
    bool voiceStage;
    int numParams;
};

inline constexpr BlockInfo blockInfo[] = {
    { "none", "None", false,  0 },
${table}
};

inline constexpr int numBlockTypes = (int) BlockType::numTypes;

inline constexpr BlockInfo info (BlockType t)
{
    const int i = (int) t;
    return (i >= 0 && i < numBlockTypes) ? blockInfo[i] : blockInfo[0];
}

inline constexpr bool isVoiceBlock (BlockType t) { return info (t).voiceStage; }

} // namespace aka::dsp
`;
}

/* ── TypeScript ───────────────────────────────────────────────────────── */

function emitTs(): string {
  const map = CATALOG.map((d, i) => `  ${JSON.stringify(d.type)}: ${i + 1},`).join("\n");

  return `// GENERATED by scripts/sync-blocks.mts — do not edit.
// Source of truth: src/model/catalog.ts. Run \`pnpm sync:blocks\`.
//
// Matches \`aka::dsp::BlockType\` one for one. Hand-maintained, this was a map of
// the eight blocks that had engines, which is exactly the thing that drifts the
// moment a ninth arrives.

/** Every block in the catalogue, whether or not it has an engine yet. */
export const BLOCK_TYPE: Record<string, number> = {
${map}
};

/** How many parameters the engine expects, in catalogue order. */
export const BLOCK_PARAMS: Record<string, number> = {
${CATALOG.map((d) => `  ${JSON.stringify(d.type)}: ${d.params.length},`).join("\n")}
};
`;
}

/* ── Run ──────────────────────────────────────────────────────────────── */

const check = process.argv.includes("--check");

const nextHeader = emitHeader();
const nextTs = emitTs();

const read = (p: string) => (fs.existsSync(p) ? fs.readFileSync(p, "utf-8") : "");

if (check) {
  const stale: string[] = [];
  if (fs.existsSync(SKELETON) && read(HEADER) !== nextHeader) stale.push(HEADER);
  if (read(TS_OUT) !== nextTs) stale.push(TS_OUT);
  if (stale.length) {
    console.error(`✗ generated block catalogue is stale:\n  ${stale.join("\n  ")}`);
    console.error("  run `pnpm sync:blocks`");
    process.exit(1);
  }
  console.log("✓ generated block catalogue matches src/model/catalog.ts");
  process.exit(0);
}

fs.mkdirSync(path.dirname(TS_OUT), { recursive: true });
fs.writeFileSync(TS_OUT, nextTs);
console.log(`✓ ${path.relative(ROOT, TS_OUT)}`);

// The skeleton is a sibling checkout. Without it the committed header still
// works; this only refreshes it.
if (fs.existsSync(SKELETON)) {
  fs.writeFileSync(HEADER, nextHeader);
  console.log(`✓ ${HEADER}`);
} else {
  console.warn(`⚠ no akaVST checkout beside this one — skipped ${path.basename(HEADER)}`);
}
